# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-12 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicinfo',
            old_name='areaInfo',
            new_name='area_data',
        ),
        migrations.RenameField(
            model_name='topicinfo',
            old_name='topicId',
            new_name='topic_id',
        ),
    ]
