# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-12 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20160512_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicinfo',
            name='area_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topicinfo',
            name='topic_id',
            field=models.IntegerField(unique=True),
        ),
    ]
