# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-12 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20160512_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinfo',
            name='comment_best',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='comment_famous',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='comment_question',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='comment_top',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='date_count',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='date_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='enetiy_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='entity_event',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='event_edge',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='event_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='event_node',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='feature_frequent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='feature_negative',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='feature_positive',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='heatmap_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='news_top',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='sentiment_piechart',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='sentiment_stream',
            field=models.TextField(null=True),
        ),
    ]
