# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20160512_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinfo',
            name='entity_profile',
            field=models.TextField(null=True),
        ),
    ]
