# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-14 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20160514_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentinfo',
            old_name='comment_news_name',
            new_name='comment_topic_name',
        ),
    ]
